import { formatCents, type BidLineItem, type ExtractionResult } from "@bidwright/shared";
import type { BidRow } from "./api";
import { computeTotals } from "./editor";

/**
 * Export builders. Kept pure (string/Blob in, string/Blob out) so the escaping
 * and money formatting are unit-testable without a DOM.
 */

/**
 * Escape one CSV field per RFC 4180: quote when the value contains a comma,
 * quote, or newline, and double any embedded quotes.
 *
 * The leading apostrophe guards against CSV injection — Excel executes a cell
 * starting with = + - @ as a formula, and ITB text ("=> see section 3") can
 * absolutely start that way.
 */
export function csvField(value: unknown): string {
  let s = value == null ? "" : String(value);
  if (/^[=+\-@\t\r]/.test(s)) s = `'${s}`;
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsvRow(fields: unknown[]): string {
  return fields.map(csvField).join(",");
}

/** CSV of line items — the format an estimator pastes into their own sheet. */
export function lineItemsToCsv(bid: {
  lineItems: BidLineItem[];
  overheadPercent: number;
  profitPercent: number;
}): string {
  const totals = computeTotals(bid.lineItems, bid.overheadPercent, bid.profitPercent);
  const rows: string[] = [
    toCsvRow(["Description", "Quantity", "Unit", "Unit Cost", "Total", "Source Page", "Notes"]),
  ];

  for (const li of bid.lineItems) {
    rows.push(
      toCsvRow([
        li.description,
        li.quantity,
        li.unit,
        (li.unitCostCents / 100).toFixed(2),
        (li.totalCostCents / 100).toFixed(2),
        li.sourcePage ?? "",
        li.notes ?? "",
      ]),
    );
  }

  rows.push(toCsvRow([]));
  rows.push(toCsvRow(["", "", "", "Subtotal", (totals.subtotalCents / 100).toFixed(2)]));
  rows.push(
    toCsvRow(["", "", "", `Overhead (${bid.overheadPercent}%)`, (totals.overheadCents / 100).toFixed(2)]),
  );
  rows.push(
    toCsvRow(["", "", "", `Profit (${bid.profitPercent}%)`, (totals.profitCents / 100).toFixed(2)]),
  );
  rows.push(toCsvRow(["", "", "", "Total", (totals.totalCents / 100).toFixed(2)]));

  return rows.join("\r\n");
}

/** A filesystem-safe basename derived from the project or ITB filename. */
export function exportFileName(bid: { projectName: string | null; itbFileName: string }, ext: string): string {
  const base = (bid.projectName ?? bid.itbFileName.replace(/\.pdf$/i, "") ?? "bid")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .toLowerCase()
    .slice(0, 60);
  return `${base || "bid"}.${ext}`;
}

export interface ProposalData {
  projectName: string;
  projectAddress: string | null;
  generalContractor: string | null;
  owner: string | null;
  bidDeadline: string | null;
  companyName: string;
  lineItems: BidLineItem[];
  assumptions: string[];
  clarifications: string[];
  exclusions: string[];
  overheadPercent: number;
  profitPercent: number;
  validityDays: number;
}

/** Flatten a bid row into the shape both the docx and pdf builders consume. */
export function toProposalData(bid: BidRow, companyName: string): ProposalData {
  const m = (bid.extraction as ExtractionResult)?.metadata;
  return {
    projectName: bid.projectName ?? bid.itbFileName,
    projectAddress: m?.projectAddress ?? null,
    generalContractor: bid.gcName ?? m?.generalContractor ?? null,
    owner: bid.ownerName ?? m?.owner ?? null,
    bidDeadline: m?.bidDeadline ?? null,
    companyName,
    lineItems: bid.lineItems ?? [],
    assumptions: bid.assumptions ?? [],
    clarifications: bid.clarifications ?? [],
    exclusions: bid.exclusions ?? [],
    overheadPercent: bid.overheadPercent,
    profitPercent: bid.profitPercent,
    validityDays: bid.validityDays,
  };
}

/** Money as it should read in a proposal. */
export function money(cents: number): string {
  return formatCents(cents);
}

/** Trigger a browser download for generated bytes. */
export function downloadBlob(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
